var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(d,c,l){if(l.get||l.set)throw new TypeError("ES3 does not support getters and setters.");d!=Array.prototype&&d!=Object.prototype&&(d[c]=l.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(d){var c=0;return $jscomp.iteratorPrototype(function(){return c<d.length?{done:!1,value:d[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};$jscomp.makeIterator=function(d){$jscomp.initSymbolIterator();var c=d[Symbol.iterator];return c?c.call(d):$jscomp.arrayIterator(d)};$jscomp.array=$jscomp.array||{};
$jscomp.iteratorFromArray=function(d,c){$jscomp.initSymbolIterator();d instanceof String&&(d+="");var l=0,g={next:function(){if(l<d.length){var e=l++;return{value:c(e,d[e]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g};
$jscomp.polyfill=function(d,c,l,g){if(c){l=$jscomp.global;d=d.split(".");for(g=0;g<d.length-1;g++){var e=d[g];e in l||(l[e]={});l=l[e]}d=d[d.length-1];g=l[d];c=c(g);c!=g&&null!=c&&$jscomp.defineProperty(l,d,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.values",function(d){return d?d:function(){return $jscomp.iteratorFromArray(this,function(c,d){return d})}},"es6","es3");
$jscomp.checkStringArgs=function(d,c,l){if(null==d)throw new TypeError("The 'this' value for String.prototype."+l+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+l+" must not be a regular expression");return d+""};$jscomp.polyfill("String.prototype.includes",function(d){return d?d:function(c,d){return-1!==$jscomp.checkStringArgs(this,c,"includes").indexOf(c,d||0)}},"es6-impl","es3");
var Parser=function(){function d(c,d,g,e,r,q){this.message=c;this.expected=d;this.found=g;this.offset=e;this.line=r;this.column=q;this.name="SyntaxError"}(function(c,d){function g(){this.constructor=c}g.prototype=d.prototype;c.prototype=new g})(d,Error);return{SyntaxError:d,parse:function(c){function l(a){if(N!==a){N>a&&(N=0,ea={line:1,column:1,seenCR:!1});var b=ea,g,u;for(g=N;g<a;g++)u=c.charAt(g),"\n"===u?(b.seenCR||b.line++,b.column=1,b.seenCR=!1):"\r"===u||"\u2028"===u||"\u2029"===u?(b.line++,
b.column=1,b.seenCR=!0):(b.column++,b.seenCR=!1);N=a}return ea}function g(b){a<U||(a>U&&(U=a,fa=[]),fa.push(b))}function e(){var c,g,h;c=a;g=q();g!==b?(h=y(),h!==b?c=g=[g,h]:(a=c,c=k)):(a=c,c=k);return c}function r(){var u,d,h,e,m,f,D,l;u=a;d=y();if(d!==b){h=a;e=[];m=w();if(m!==b)for(;m!==b;)e.push(m),m=w();else e=k;if(e!==b){m=a;f=t();if(f!==b){D=[];l=w();if(l!==b)for(;l!==b;)D.push(l),l=w();else D=k;D!==b?m=f=[f,D]:(a=m,m=k)}else a=m,m=k;m===b&&(m=H);m!==b?h=e=[e,m]:(a=h,h=k)}else a=h,h=k;if(h===
b)if(h=a,e=t(),e!==b){m=[];f=w();if(f!==b)for(;f!==b;)m.push(f),f=w();else m=k;m!==b?h=e=[e,m]:(a=h,h=k)}else a=h,h=k;h!==b&&(h="number");if(h===b){h=a;34===c.charCodeAt(a)?(e=ga,a++):(e=b,0===n&&g(ha));if(e!==b){e=[];ia.test(c.charAt(a))?(m=c.charAt(a),a++):(m=b,0===n&&g(ja));for(;m!==b;)e.push(m),ia.test(c.charAt(a))?(m=c.charAt(a),a++):(m=b,0===n&&g(ja));e!==b?(34===c.charCodeAt(a)?(m=ga,a++):(m=b,0===n&&g(ha)),m!==b?h="str":(a=h,h=k)):(a=h,h=k)}else a=h,h=k;if(h===b){h=a;39===c.charCodeAt(a)?
(e=ka,a++):(e=b,0===n&&g(la));if(e!==b){e=[];ma.test(c.charAt(a))?(m=c.charAt(a),a++):(m=b,0===n&&g(na));for(;m!==b;)e.push(m),ma.test(c.charAt(a))?(m=c.charAt(a),a++):(m=b,0===n&&g(na));e!==b?(39===c.charCodeAt(a)?(m=ka,a++):(m=b,0===n&&g(la)),m!==b?h="str":(a=h,h=k)):(a=h,h=k)}else a=h,h=k;h===b&&(h=oa())}}if(h===b){h=[];pa.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(qa));if(e!==b)for(;e!==b;)h.push(e),pa.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(qa));else h=k;h!==b&&(h="name");
h===b&&(e=h=a,m=y(),m!==b?(45===c.charCodeAt(a)?(f=ra,a++):(f=b,0===n&&g(sa)),f===b&&(43===c.charCodeAt(a)?(f=ta,a++):(f=b,0===n&&g(ua)),f===b&&(126===c.charCodeAt(a)?(f=Pa,a++):(f=b,0===n&&g(Qa)),f===b&&(f=va()))),f!==b?e=m=[m,f]:(a=e,e=k)):(a=e,e=k),e!==b?(m=q(),m!==b?h=e=[e,m]:(a=h,h=k)):(a=h,h=k),h===b&&(h=a,e=y(),e!==b?(m=E(),m!==b?(f=q(),f!==b?(D=y(),D!==b?(l=O(),l!==b?h=e=[e,m,f,D,l]:(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k)))}h!==b?u=d=[d,h]:(a=u,u=k)}else a=u,u=k;return u}function q(){var u,
d,h,e,m,f,l,p,I,B,x,t,w;u=a;d=y();if(d!==b){h=a;e=r();e!==b?(m=a,f=y(),f!==b?(c.substr(a,2)===wa?(f=wa,a+=2):(f=b,0===n&&g(Ra)),f===b&&(42===c.charCodeAt(a)?(f=Sa,a++):(f=b,0===n&&g(Ta)),f===b&&(47===c.charCodeAt(a)?(f=Ua,a++):(f=b,0===n&&g(Va)),f===b&&(37===c.charCodeAt(a)?(f=Wa,a++):(f=b,0===n&&g(Xa)),f===b&&(43===c.charCodeAt(a)?(f=ta,a++):(f=b,0===n&&g(ua)),f===b&&(45===c.charCodeAt(a)?(f=ra,a++):(f=b,0===n&&g(sa)),f===b&&(c.substr(a,2)===xa?(f=xa,a+=2):(f=b,0===n&&g(Ya)),f===b&&(c.substr(a,2)===
ya?(f=ya,a+=2):(f=b,0===n&&g(Za)),f===b&&(38===c.charCodeAt(a)?(f=$a,a++):(f=b,0===n&&g(ab)),f===b&&(124===c.charCodeAt(a)?(f=bb,a++):(f=b,0===n&&g(cb)),f===b&&(c.substr(a,2)===za?(f=za,a+=2):(f=b,0===n&&g(eb)),f===b&&(c.substr(a,2)===Aa?(f=Aa,a+=2):(f=b,0===n&&g(fb)),f===b&&(60===c.charCodeAt(a)?(f=gb,a++):(f=b,0===n&&g(hb)),f===b&&(62===c.charCodeAt(a)?(f=ib,a++):(f=b,0===n&&g(jb)),f===b&&(61===c.charCodeAt(a)?(f=kb,a++):(f=b,0===n&&g(lb)),f===b&&(c.substr(a,2)===Ba?(f=Ba,a+=2):(f=b,0===n&&g(mb)),
f===b&&(c.substr(a,2)===Ca?(f=Ca,a+=2):(f=b,0===n&&g(nb)),f===b&&(c.substr(a,2)===Da?(f=Da,a+=2):(f=b,0===n&&g(ob)),f===b&&(f=a,l=A(),l!==b?(p=J(),p===b&&(p=H),p!==b?f=l=[l,p]:(a=f,f=k)):(a=f,f=k),f===b&&(f=Ea(),f===b&&(f=C(),f===b&&(f=V(),f===b&&(f=z(),f===b&&(f=K(),f===b&&(f=a,W.test(c.charAt(a))?(l=c.charAt(a),a++):(l=b,0===n&&g(X)),l!==b?(Fa.test(c.charAt(a))?(p=c.charAt(a),a++):(p=b,0===n&&g(Ga)),p!==b?f=l=[l,p]:(a=f,f=k)):(a=f,f=k))))))))))))))))))))))))),f!==b?m="op":(a=m,m=k)):(a=m,m=k),m!==
b?(f=q(),f!==b?h=e=[e,m,f]:(a=h,h=k)):(a=h,h=k)):(a=h,h=k);if(h===b&&(h=a,e=r(),e!==b?(m=J(),m===b&&(m=H),m!==b?(f=v(),f!==b?(l=C(),l===b&&(l=z(),l===b&&(l=V())),l!==b?(p=q(),p!==b?h=e=[e,m,f,l,p]:(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k),h===b&&(h=a,e=r(),e!==b?(m=a,f=v(),f!==b?(Y.test(c.charAt(a))?(f=c.charAt(a),a++):(f=b,0===n&&g(Z)),f!==b?(Ha.test(c.charAt(a))?(f=c.charAt(a),a++):(f=b,0===n&&g(Ia)),f!==b?(F.test(c.charAt(a))?(f=c.charAt(a),a++):(f=b,0===n&&g(G)),f!==b?(W.test(c.charAt(a))?
(f=c.charAt(a),a++):(f=b,0===n&&g(X)),f!==b?(P.test(c.charAt(a))?(f=c.charAt(a),a++):(f=b,0===n&&g(Q)),f!==b?m=0:(a=m,m=k)):(a=m,m=k)):(a=m,m=k)):(a=m,m=k)):(a=m,m=k)):(a=m,m=k),m===b&&(m=a,f=v(),f!==b?(F.test(c.charAt(a))?(f=c.charAt(a),a++):(f=b,0===n&&g(G)),f!==b?(W.test(c.charAt(a))?(f=c.charAt(a),a++):(f=b,0===n&&g(X)),f!==b?(P.test(c.charAt(a))?(f=c.charAt(a),a++):(f=b,0===n&&g(Q)),f!==b?(F.test(c.charAt(a))?(f=c.charAt(a),a++):(f=b,0===n&&g(G)),f!==b?(Ja.test(c.charAt(a))?(f=c.charAt(a),a++):
(f=b,0===n&&g(Ka)),f!==b?(R.test(c.charAt(a))?(f=c.charAt(a),a++):(f=b,0===n&&g(S)),f!==b?(R.test(c.charAt(a))?(f=c.charAt(a),a++):(f=b,0===n&&g(S)),f!==b?m=1:(a=m,m=k)):(a=m,m=k)):(a=m,m=k)):(a=m,m=k)):(a=m,m=k)):(a=m,m=k)):(a=m,m=k)):(a=m,m=k),m===b&&(m=a,f=J(),f!==b?(l=oa(),l!==b?m=f=[f,l]:(a=m,m=k)):(a=m,m=k))),m!==b?h=e=[e,m]:(a=h,h=k)):(a=h,h=k),h===b&&(h=a,e=r(),e!==b?(m=v(),m!==b?(f=A(),f!==b?(l=J(),l===b&&(l=H),l!==b?(p=q(),p!==b?h=e=[e,m,f,l,p]:(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):
(a=h,h=k),h===b&&(h=a,e=r(),e!==b?(m=J(),m===b&&(m=H),m!==b?(f=a,l=v(),l!==b?(pb.test(c.charAt(a))?(l=c.charAt(a),a++):(l=b,0===n&&g(qb)),l!==b?(L.test(c.charAt(a))?(l=c.charAt(a),a++):(l=b,0===n&&g(M)),l!==b?(P.test(c.charAt(a))?(l=c.charAt(a),a++):(l=b,0===n&&g(Q)),l!==b?(rb.test(c.charAt(a))?(l=c.charAt(a),a++):(l=b,0===n&&g(sb)),l!==b?(L.test(c.charAt(a))?(l=c.charAt(a),a++):(l=b,0===n&&g(M)),l!==b?(L.test(c.charAt(a))?(l=c.charAt(a),a++):(l=b,0===n&&g(M)),l!==b?(F.test(c.charAt(a))?(l=c.charAt(a),
a++):(l=b,0===n&&g(G)),l!==b?f=0:(a=f,f=k)):(a=f,f=k)):(a=f,f=k)):(a=f,f=k)):(a=f,f=k)):(a=f,f=k)):(a=f,f=k)):(a=f,f=k),f!==b?(l=q(),l!==b?(p=v(),p!==b?(I=K(),I!==b?(B=q(),B!==b?h=e=[e,m,f,l,p,I,B]:(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k),h===b))))){h=a;e=r();if(e!==b)if(m=J(),m===b&&(m=H),m!==b)if(f=v(),f!==b)if(l=Ea(),l!==b){p=a;I=E();if(I!==b){B=[];x=a;t=q();t!==b?(w=T(),w!==b?x=t=[t,w]:(a=x,x=k)):(a=x,x=k);if(x!==b)for(;x!==b;)B.push(x),x=a,t=q(),t!==b?(w=T(),
w!==b?x=t=[t,w]:(a=x,x=k)):(a=x,x=k);else B=k;B===b&&(B=H);B!==b?(x=O(),x!==b?p=I=[I,B,x]:(a=p,p=k)):(a=p,p=k)}else a=p,p=k;p!==b?h=e=[e,m,f,l,p]:(a=h,h=k)}else a=h,h=k;else a=h,h=k;else a=h,h=k;else a=h,h=k;h===b&&(h=r())}h!==b?u=d=[d,h]:(a=u,u=k)}else a=u,u=k;return u}function y(){var d,e;d=[];aa.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(ba));for(;e!==b;)d.push(e),aa.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(ba));return d}function v(){var d,e;d=[];aa.test(c.charAt(a))?(e=c.charAt(a),
a++):(e=b,0===n&&g(ba));if(e!==b)for(;e!==b;)d.push(e),aa.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(ba));else d=k;return d}function w(){var d;tb.test(c.charAt(a))?(d=c.charAt(a),a++):(d=b,0===n&&g(ub));return d}function t(){var d;46===c.charCodeAt(a)?(d=vb,a++):(d=b,0===n&&g(wb));return d}function T(){var d;44===c.charCodeAt(a)?(d=xb,a++):(d=b,0===n&&g(yb));return d}function E(){var d;40===c.charCodeAt(a)?(d=zb,a++):(d=b,0===n&&g(Ab));return d}function O(){var d;41===c.charCodeAt(a)?(d=
Bb,a++):(d=b,0===n&&g(Cb));return d}function K(){var d,e;d=a;La.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Ma));e!==b?(F.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(G)),e!==b?(Db.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Eb)),e!==b?d=0:(a=d,d=k)):(a=d,d=k)):(a=d,d=k);return d}function A(){var d,e;d=a;Y.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Z));e!==b?(Ha.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Ia)),e!==b?d=3:(a=d,d=k)):(a=d,d=k);return d}function z(){var d,
e;d=a;Fa.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Ga));e!==b?(L.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(M)),e!==b?(Fb.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Gb)),e!==b?(L.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(M)),e!==b?(Hb.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Ib)),e!==b?(Jb.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Kb)),e!==b?d=0:(a=d,d=k)):(a=d,d=k)):(a=d,d=k)):(a=d,d=k)):(a=d,d=k)):(a=d,d=k);return d}function C(){var d,e;
d=a;R.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(S));e!==b?(Y.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Z)),e!==b?(Lb.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Mb)),e!==b?(L.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(M)),e!==b?d=0:(a=d,d=k)):(a=d,d=k)):(a=d,d=k)):(a=d,d=k);return d}function V(){var d,e;d=a;Nb.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Ob));e!==b?(La.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Ma)),e!==b?(P.test(c.charAt(a))?(e=
c.charAt(a),a++):(e=b,0===n&&g(Q)),e!==b?(Pb.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Qb)),e!==b?(Rb.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Sb)),e!==b?d=0:(a=d,d=k)):(a=d,d=k)):(a=d,d=k)):(a=d,d=k)):(a=d,d=k);return d}function Ea(){var d,e;d=a;Y.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Z));e!==b?(F.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(G)),e!==b?d=3:(a=d,d=k)):(a=d,d=k);return d}function va(){var d,e;d=a;F.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,
0===n&&g(G));e!==b?(W.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(X)),e!==b?(P.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Q)),e!==b?d=0:(a=d,d=k)):(a=d,d=k)):(a=d,d=k);return d}function J(){var c,d;c=a;d=v();d!==b?(d=va(),d!==b?c=0:(a=c,c=k)):(a=c,c=k);return c}function oa(){var d,e;d=a;e=v();e!==b?(F.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(G)),e!==b?(Ja.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(Ka)),e!==b?(R.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&
g(S)),e!==b?(R.test(c.charAt(a))?(e=c.charAt(a),a++):(e=b,0===n&&g(S)),e!==b?d=2:(a=d,d=k)):(a=d,d=k)):(a=d,d=k)):(a=d,d=k)):(a=d,d=k);return d}var ca=1<arguments.length?arguments[1]:{},b={},Na={start:e},Oa=e,k=b,H=null,aa=/^[ \t\n\r]/,ba={type:"class",value:"[ \\t\\n\\r]",description:"[ \\t\\n\\r]"},ra="-",sa={type:"literal",value:"-",description:'"-"'},ta="+",ua={type:"literal",value:"+",description:'"+"'},Pa="~",Qa={type:"literal",value:"~",description:'"~"'},wa="||",Ra={type:"literal",value:"||",
description:'"||"'},Sa="*",Ta={type:"literal",value:"*",description:'"*"'},Ua="/",Va={type:"literal",value:"/",description:'"/"'},Wa="%",Xa={type:"literal",value:"%",description:'"%"'},xa="<<",Ya={type:"literal",value:"<<",description:'"<<"'},ya=">>",Za={type:"literal",value:">>",description:'">>"'},$a="&",ab={type:"literal",value:"&",description:'"&"'},bb="|",cb={type:"literal",value:"|",description:'"|"'},za="<=",eb={type:"literal",value:"<=",description:'"<="'},Aa=">=",fb={type:"literal",value:">=",
description:'">="'},gb="<",hb={type:"literal",value:"<",description:'"<"'},ib=">",jb={type:"literal",value:">",description:'">"'},kb="=",lb={type:"literal",value:"=",description:'"="'},Ba="==",mb={type:"literal",value:"==",description:'"=="'},Ca="!=",nb={type:"literal",value:"!=",description:'"!="'},Da="<>",ob={type:"literal",value:"<>",description:'"<>"'},W=/^[oO]/,X={type:"class",value:"[oO]",description:"[oO]"},Fa=/^[rR]/,Ga={type:"class",value:"[rR]",description:"[rR]"},tb=/^[0-9]/,ub={type:"class",
value:"[0-9]",description:"[0-9]"},pa=/^[A-Za-z0-9_]/,qa={type:"class",value:"[A-Za-z0-9_]",description:"[A-Za-z0-9_]"},vb=".",wb={type:"literal",value:".",description:'"."'},xb=",",yb={type:"literal",value:",",description:'","'},zb="(",Ab={type:"literal",value:"(",description:'"("'},Bb=")",Cb={type:"literal",value:")",description:'")"'},ga='"',ha={type:"literal",value:'"',description:'"\\""'},ia=/^[^"]/,ja={type:"class",value:'[^"]',description:'[^"]'},ka="'",la={type:"literal",value:"'",description:'"\'"'},
ma=/^[^']/,na={type:"class",value:"[^']",description:"[^']"},La=/^[aA]/,Ma={type:"class",value:"[aA]",description:"[aA]"},F=/^[nN]/,G={type:"class",value:"[nN]",description:"[nN]"},Db=/^[dD]/,Eb={type:"class",value:"[dD]",description:"[dD]"},Y=/^[iI]/,Z={type:"class",value:"[iI]",description:"[iI]"},Ha=/^[sS]/,Ia={type:"class",value:"[sS]",description:"[sS]"},L=/^[eE]/,M={type:"class",value:"[eE]",description:"[eE]"},Fb=/^[gG]/,Gb={type:"class",value:"[gG]",description:"[gG]"},Hb=/^[xX]/,Ib={type:"class",
value:"[xX]",description:"[xX]"},Jb=/^[pX]/,Kb={type:"class",value:"[pX]",description:"[pX]"},R=/^[lL]/,S={type:"class",value:"[lL]",description:"[lL]"},Lb=/^[kK]/,Mb={type:"class",value:"[kK]",description:"[kK]"},Nb=/^[mM]/,Ob={type:"class",value:"[mM]",description:"[mM]"},P=/^[tT]/,Q={type:"class",value:"[tT]",description:"[tT]"},Pb=/^[cC]/,Qb={type:"class",value:"[cC]",description:"[cC]"},Rb=/^[hH]/,Sb={type:"class",value:"[hH]",description:"[hH]"},Ja=/^[uU]/,Ka={type:"class",value:"[uU]",description:"[uU]"},
pb=/^[bB]/,qb={type:"class",value:"[bB]",description:"[bB]"},rb=/^[wW]/,sb={type:"class",value:"[wW]",description:"[wW]"},a=0,N=0,ea={line:1,column:1,seenCR:!1},U=0,fa=[],n=0,da;if("startRule"in ca){if(!(ca.startRule in Na))throw Error("Can't start parsing from rule \""+ca.startRule+'".');Oa=Na[ca.startRule]}da=Oa();if(da!==b&&a===c.length)return da;da!==b&&a<c.length&&g({type:"end",description:"end of input"});throw function(a,b,e){function g(a){var b=1;for(a.sort(function(a,b){return a.description<
b.description?-1:a.description>b.description?1:0});b<a.length;)a[b-1]===a[b]?a.splice(b,1):b++}function h(a,b){function c(a){function b(a){return a.charCodeAt(0).toString(16).toUpperCase()}return a.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\x08/g,"\\b").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\f/g,"\\f").replace(/\r/g,"\\r").replace(/[\x00-\x07\x0B\x0E\x0F]/g,function(a){return"\\x0"+b(a)}).replace(/[\x10-\x1F\x80-\xFF]/g,function(a){return"\\x"+b(a)}).replace(/[\u0180-\u0FFF]/g,
function(a){return"\\u0"+b(a)}).replace(/[\u1080-\uFFFF]/g,function(a){return"\\u"+b(a)})}var d=Array(a.length),e;for(e=0;e<a.length;e++)d[e]=a[e].description;a=1<a.length?d.slice(0,-1).join(", ")+" or "+d[a.length-1]:d[0];b=b?'"'+c(b)+'"':"end of input";return"Expected "+a+" but "+b+" found."}var f=l(e),k=e<c.length?c.charAt(e):null;null!==b&&g(b);return new d(null!==a?a:h(b,k),b,k,e,f.line,f.column)}(null,fa,U);}}}(),importSql=function(){var d=function(d){return" "===d||"\t"===d||"\n"===d||"\v"===
d||"\f"===d||"\r"===d},c=function(c){for(var e=0;e<c.length;e++)if(!d(c[e]))if("/"==c[e]&&"*"==c[e+1]){for(e+=2;e<c.length&&("*"!=c[e]||"/"!=c[e+1]);)e++;if(e==c.length)return!1;e++}else if("-"==c[e]&&"-"==c[e+1]){for(e+=2;e<c.length&&"\n"!=c[e];)e++;if(e==c.length)break}else return!1;return!0},l=0;return function(g){l=0;var e=(new FileReaderSync).readAsText(g.file);g.transaction&&db.exec("BEGIN TRANSACTION");var r;try{for(var q={id:g.id,partialResponse:!0},y=e.split("\n"),v=e="",w,t=0,T=0,E=0,O=
(new Date).getTime(),K;E<y.length;)if(e=y[E],K=(new Date).getTime(),100<=K-O&&(q.progress=E/y.length,postMessage(q),O=K),E++,0!=t||!c(e)){for(var A=e,z=0;d(A[z]);)z++;(z<A.length&&"/"==A[z]&&c(A.substr(z+1))||z<A.length&&"g"==A[z].toLowerCase()&&"o"==A[z+1].toLowerCase()&&c(A.substr(z+2)))&&(v?SQL.isComplete(v+";"):1)&&(e=";");w=e.length;T=t;if(0==t){var C;for(C=0;C<w&&d(e[C]);C++);v=e.substr(C);l=E;t=w-C}else v=v+"\n"+e,t=t+1+w;0<t&&-1<v.substring(T).indexOf(";")&&SQL.isComplete(v)?(db.exec(v),t=
0):0<t&&c(v)&&(t=0)}if(0<t&&!c(v))throw{message:"Incomplete SQL: "+v};r={done:!0};g.transaction&&db.exec("COMMIT TRANSACTION")}catch(V){g.transaction&&db.exec("ROLLBACK TRANSACTION"),r={error:V.message,line:l}}return r}}(),parseMimeType=function(){var d={},c=function(c,g){for(var e=d,l=0;l<g.length;l++)e[g[l]]||(e[g[l]]={}),e=e[g[l]];e.type=c};c("mp4",[0,0,0,"skip",102,116,121,112]);c("mp4",[51,103,112,53]);c("gif",[71,73,70,56,55,97]);c("gif",[71,73,70,56,57,97]);c("jpg",[255,216,255,224]);c("jpg",
[255,216,255,225]);c("jpg",[255,216,255,226]);c("jpg",[255,216,255,227]);c("jpg",[255,216,255,232]);c("zip",[80,75,3,4]);c("zip",[80,75,5,6]);c("zip",[80,75,7,8]);c("rar",[82,97,114,33,26,7,0]);c("rar",[82,97,114,33,26,7,1,0]);c("png",[137,80,78,71,13,10,26,10]);c("pdf",[37,80,68,70]);c("ogg",[79,103,103,83]);c("psd",[56,66,80,83]);c("mp3",[255,251]);c("mp3",[73,68,51]);c("bmp",[66,77]);c("mid",[77,84,104,100]);c("tar",[117,115,116,97,114,0,48,48]);c("tar",[117,115,116,97,114,32,32,0]);c("7z",[55,
122,188,175,39,28]);c("wav",[82,73,70,70,"skip","skip","skip","skip",87,65,86,69]);return function(c){for(var g=d,e=0;e<c.length;e++)if(g[c[e]]){if(g=g[c[e]],g.type)return g.type}else if(g.skip)g=g.skip;else break;return null}}();importScripts("../third_party/sql/sql.js");var db,cachedUrls=[];SQL.Statement.prototype.parseBlob=function(d){var c=parseMimeType(d);c||(c="blob");var l=URL.createObjectURL(new Blob([d]));cachedUrls.push(l);return{blobUrl:l,blobType:c,length:d.length}};
function openDb(d){if(d){var c=new FileReaderSync;db=new SQL.Database(new Uint8Array(c.readAsArrayBuffer(d)))}else db=new SQL.Database;return reloadMasterTable()}function reloadMasterTable(){return db.exec("SELECT name, type FROM sqlite_master")}
var handleCommand=function(d){if(!d.preserveBlobs&&0<cachedUrls.length){for(var c=0;c<cachedUrls.length;c++)URL.revokeObjectURL(cachedUrls[c]);cachedUrls=[]}switch(d.action){case "open":return openDb(d.file);case "reload":return reloadMasterTable();case "exec":if(d.query){try{Parser.parse(d.query)}catch(l){throw{message:"Invalid search params"};}d.sql=d.sql+" where "+d.query}return db.exec(d.sql);case "load":return loadTable(d.name);case "statement":return runStatement(d);case "export":return exportData(d);
case "exportCSV":return exportCSV(d);case "exportDB":return exportDB(d);case "import":return importSql(d)}},runStatement=function(d){var c=db.prepare(d.sql);c.run(sanitizeArgs(d.args));c.free();if(!d.resultSql)return{result:"OK"};c=db.prepare(d.resultSql);d=c.get(sanitizeArgs(d.resultArgs));c.free();return d},sanitizeArgs=function(d){for(var c=0;c<d.length;c++)if(d[c]instanceof File){var l=(new FileReaderSync).readAsArrayBuffer(d[c]);d[c]=new Uint8Array(l)}else if(null!=d[c]&&d[c].blobType)if(l=new XMLHttpRequest,
l.open("GET",d[c].blobUrl,!1),l.responseType="arraybuffer",l.send(null),200===l.status)d[c]=new Uint8Array(l.response);else throw{message:"Error loading blob"};return d},loadTable=function(d){for(var c=db.exec("PRAGMA table_info("+escapeSql(d)+")")[0],l=c.columns.indexOf("pk"),g=!1,e=0;e<c.values.length;e++)if(1==c.values[e][l]){g=!0;break}d=(g?"select * from ":"select rowid, * from ")+escapeSql(d);e=db.exec(d)[0];if(!e){var r=[];g||r.push("rowid");for(var q=c.columns.indexOf("name"),e=0;e<c.values.length;e++)r.push(c.values[e][q]);
e={columns:r,values:[]}}return{0:e,1:c,hasPrimaryKey:g,baseSql:d,pkIndex:l}},exportData=function(d){for(var c="",l=db.exec("SELECT type, name, sql FROM sqlite_master")[0].values,g="",e=0;e<l.length;e++)if(-1!=d.type.indexOf(l[e][0])){var r=escapeSql(l[e][1]),c=c+("DROP "+l[e][0].toUpperCase()+" IF EXISTS "+r+";\n"),g=g+(l[e][2]+";\n");if(d.includeData&&"TABLE"==l[e][0].toUpperCase()){var q=db.prepare("SELECT * from "+r);for(q.parseBlob=function(c){return c};q.step();)var y=q.get().map(exportDataMapper).join(","),
g=g+("INSERT INTO "+r+" VALUES("+y+");\n");q.free()}}d.includeDrop&&(g=c+g);return{blob:new Blob([g],{type:"text/plain"})}},exportCSV=function(d){var c=d.seperator,l;if(2==d.enclosing)l=function(c){return c};else{var g=function(c){return'"'+c.replace(/"/g,'""')+'"'};l=1==d.enclosing?g:function(d){return d.includes('"')||d.includes(c)?g(d):d}}var e=function(c){if(null==c)return"";if(c.blobUrl){var d=new XMLHttpRequest;d.open("GET",c.blobUrl,!1);d.responseType="arraybuffer";d.send(null);return 200!=
d.status?"[BLOB]":unit8ArrayMapper(new Uint8Array(d.response))}return c+""},r="";d.includeHeader&&(r=d.data.columns.map(e).map(l).join(c)+"\n");d=$jscomp.makeIterator(d.data.values);for(var q=d.next();!q.done;q=d.next())r+=q.value.map(e).map(l).join(c)+"\n";return{blob:new Blob([r],{type:"data:text/csv"})}},unit8ArrayMapper=function(d){for(var c="",l=0;l<d.length;l++)var g=d[l].toString(16),c=c+(2>g.length?"0"+g:g);return"X'"+c+"'"},exportDataMapper=function(d){return null==d?"NULL":"string"==typeof d?
escapeSql(d):d instanceof Uint8Array?unit8ArrayMapper(d):d},exportDB=function(d){return{blob:new Blob([db.export()])}};self.onmessage=function(d){var c;try{c=handleCommand(d.data)}catch(l){c={error:l.message}}c.id=d.data.id;return postMessage(c)};var escapeSql=function(d){return"'"+d.replace(/'/g,"''")+"'"};
